Repository studie-tech/TheNinjaRPG, pull requests merged in 2025-02, with the labels that each got.

#358 Fix Issue #357: Unable to create AI after implementation of Offensive and General preferences
  app/src/app/layout.tsx
  app/src/env/schema.mjs
Labels: Completed

#360 Fix Issue #359: Filtering broke during recent updates
  app/src/layout/JutsuFiltering.tsx
Labels: bug, Completed

#362 Fix issue #361: Make ElementalSeal cleansable
  app/src/libs/combat/types.ts
Labels: bug, Completed

#372 Fix Issue #371: Basic Clear/Cleanse text is reversed
  app/src/libs/combat/actions.ts
Labels: Completed

#377 Fix Issue #370: Reduce from 50 members to 30 for town upgrade.
  app/drizzle/constants.ts
Labels: Completed

#383 Fix issue #382: Achievement Tab
  app/drizzle/constants.ts
  app/drizzle/migrations/0196_brave_the_hunter.sql
  app/drizzle/migrations/meta/0196_snapshot.json
  app/drizzle/migrations/meta/_journal.json
  app/src/layout/Logbook.tsx
  app/src/libs/profile.ts
  app/src/libs/replicate.ts
  app/src/libs/train.ts
  app/src/server/api/routers/jutsu.ts
  app/src/validators/objectives.ts
Labels: Completed

#381 Fix issue #380: Player being Silenced is still able to Talk in Tavern
  app/src/layout/Conversation.tsx
  app/src/libs/combat/process.ts
  app/src/libs/quest.ts
Labels: bug, Needs additional work, Priority

#343 Fix issue #342: Drain
  app/src/app/jutsus/page.tsx
  app/src/libs/combat/process.ts
  app/src/libs/combat/tags.ts
  app/src/libs/combat/types.ts
  app/src/libs/combat/util.ts
Labels: Completed, Jutsu Tag, Medium Priority
